#!/bin/sh

killall -q softnic
sleep 1
if lsmod | grep -q softnic; then
	sudo rmmod softnic || exit 0
fi

make && sudo insmod softnic.ko && echo "Module successfully installed!"
sudo chmod 0444 /dev/softnic
sudo perf buildid-cache -a softnic.ko
