#- include: packages.yml

- hosts: all
  tags: build-bess
  tasks:
    - shell: ls -d /sys/devices/system/node/node* | wc -l
      register: num_nodes

    - shell: cat /proc/meminfo | grep Hugepagesize
      register: def_hugepage_size

    - name: Enable huge pages
      sysctl: name=vm.nr_hugepages value={{ num_nodes.stdout|int * 1024 }} sysctl_set=yes
      when: "{{ def_hugepage_size.stdout.find('2048 kB') != -1 }}"
      become: true

    - shell: mount | grep 'type hugetlbfs'
      register: hugetlbfs_mounted
      failed_when: hugetlbfs_mounted.rc == 2

    - name: Mount up /mnt/huge
      mount: name=/mnt/huge fstype=hugetlbfs src=none state=mounted
      when: hugetlbfs_mounted.rc == 1
      become: true

    - name: Clone BESS repository
      git: repo=https://github.com/NetSys/bess.git dest={{ ansible_env.HOME }}/bess accept_hostkey=yes

    - name: Build BESS (this may take a while)
      shell: ./build.py chdir={{ ansible_env.HOME }}/bess
