- hosts: all
  tags: build-dep
  tasks:
    - apt_repository: repo='ppa:ubuntu-toolchain-r/test' codename={{ ansible_distribution_release }}
      become: true
      when: ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int < 18

    - name: Install prerequisite packages
      apt: name={{item}} update_cache=yes
      become: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - g++
        - g++-7
        - make
        - libunwind8-dev
        - liblzma-dev
        - zlib1g-dev
        - libpcap-dev
        - libssl-dev
        - libnuma-dev
        - libgflags-dev
        - libgoogle-glog-dev
        - libgtest-dev
        - python3
        - python3-pip
        - python3-setuptools
        - pkg-config

    - name: Install DPDK build system
      become: true
      pip:
        name:
          - meson
          - ninja
        executable: pip3

    # pre-packaged meat for Bionic Beaver or higher
    - name: Install gRPC and its requirements (apt)
      apt: name={{item}}
      become: true
      with_items:
        - libc-ares-dev
        - libbenchmark-dev
        - libgrpc++-dev
        - libprotobuf-dev
        - protobuf-compiler-grpc
      when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 18)

    # for Ubuntu < 18.04, grpc has to be installed manually
    - name: Install gRPC and its requirements (from source)
      block:
        - name: Install grpc denepdencies
          apt: name={{item}}
          become: true
          with_items:
            - autoconf
            - libtool
            - cmake

        - name: Download gRPC
          git: repo=https://github.com/google/grpc dest=/tmp/grpc accept_hostkey=yes version=v1.3.2

        - name: Compile gRPC and its dependencies
          shell: make -j`nproc` EXTRA_CFLAGS='-Wno-error' HAS_SYSTEM_PROTOBUF=false chdir=/tmp/grpc

        - name: Install gRPC
          shell: make install chdir=/tmp/grpc

        - name: Install protobuf
          shell: make install chdir=/tmp/grpc/third_party/protobuf

        - name: Generate makefile for libbenchmark
          shell: cmake . chdir=/tmp/grpc/third_party/benchmark

        - name: Install libbenchmark
          shell: make install chdir=/tmp/grpc/third_party/benchmark

        - name: sudo ldconfig
          shell: ldconfig
      become: true
      when: ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int < 18

    - name: BESS build dependencies installed
      debug:
        msg: "You are now ready to build BESS using build.py"
