- hosts: all
  tags: package
  tasks:
    - apt_repository: repo='ppa:ubuntu-toolchain-r/test' state=present
      become: true

    - name: Install list of packages (this step may take a long time)
      apt: name={{item}} state=latest update_cache=yes
      become: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - build-essential
        - g++-4.8
        - g++-5
        - g++-6
        - g++
        - clang-3.8
        - autoconf
        - automake
        - libtool
        - make
        - cmake
        - libpthread-stubs0-dev
        - libunwind8-dev
        - liblzma-dev
        - zlib1g-dev
        - libpcap-dev
        - libssl-dev
        - curl
        - git
        - python
        - python-dev
        - python-pip
        - python-scapy
        - libgflags-dev
        - libgoogle-glog-dev
        - libgraph-easy-perl
        - libgtest-dev
        - linux-headers-generic
        - lcov
        - python-autopep8

    - name: Install release-specific packages
      apt: name={{item}} state=latest update_cache=yes
      become: true
      with_items:
        - python-pep8
      when: ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16

    - name: Install Linux headers of current running kernel
      apt: name=linux-headers-{{ ansible_kernel }} state=latest update_cache=yes
      become: true
      when: ansible_kernel | match(".*-generic")

    - name: Install list of Python packages
      pip: name=grpcio
      become: true

    - name: Wipe prior protobuf installs to avoid conflicts
      shell: apt-get remove -y -f libprotobuf* protobuf-* protoc; sudo rm -f `which protoc` warn=no
      become: true

    - name: sudo ldconfig
      shell: ldconfig
      become: true

    - name: Download gRPC
      git: repo=https://github.com/google/grpc dest=/tmp/grpc accept_hostkey=yes version=v1.3.2

    - name: Compile gRPC and its dependencies
      shell: make -j{{ ansible_processor_vcpus }} chdir=/tmp/grpc

    - name: Install gRPC
      shell: make install chdir=/tmp/grpc
      become: true

    - name: Install protobuf
      shell: make install chdir=/tmp/grpc/third_party/protobuf
      become: true

    - name: Generate makefile for libbenchmark
      shell: cmake . chdir=/tmp/grpc/third_party/benchmark

    - name: Install libbenchmark
      shell: make install chdir=/tmp/grpc/third_party/benchmark
      become: true

    - name: sudo ldconfig
      shell: ldconfig
      become: true
