name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo sysctl -w vm.nr_hugepages=512
      - run: 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test'
      - run: sudo apt-get -q update
      - run: >-
          sudo apt-get install -y python2.7 python3 python3-pip
          python3-setuptools ruby-dev
      - run: sudo gem install ffi fpm
      - run: pip2 install --user -r requirements.txt codecov
      - run: pip3 install --user -r requirements.txt coverage
      - run: '[[ ${COVERAGE:-0} == 0 ]] || sudo apt-get install -y gcc-7'
      - run: '[[ ${SANITIZE:-0} == 0 ]] || sudo apt-get install -y llvm-3.9'
      - run: 'docker pull nefelinetworks/bess_build:latest${TAG_SUFFIX} | cat'
      - run: sudo mkdir -p /mnt/huge
      - run: sudo mount -t hugetlbfs nodev /mnt/huge
      - run: export CXX="ccache $VER_CXX"
      - run: ccache -s
      - run: travis_wait 30 ./container_build.py bess
      - run: ./container_build.py kmod_buildtest
      - run: (cd core && ./all_test --gtest_shuffle)
      - run: coverage2 run -m unittest discover -v
      - run: '[[ ${COVERAGE:-0} == 0 ]] || coverage3 run -m unittest discover -v'
      - run: python2 bessctl/run_module_tests.py
      - run: '[[ ${COVERAGE:-0} == 0 ]] || python3 bessctl/run_module_tests.py'
      - run: ccache -s
      - run: bessctl/bessctl daemon stop
      - run: '[[ ${COVERAGE:-0} == 0 ]] || { sleep 3; codecov --gcov-exec gcov-7; }'
